### ISSUE TITLE
Addition of Meta Tags (SEO Optimization)

### ISSUE THREAD

**Issue by BowlPulp** [Open-Source-Chandigarh/SearchMovies#11]
The website doesn't have any meta header tags that specify the description, image, and other relevant information about the project, which is important for users to know while sharing.
This is how it currently looks - 
![{65E66F6C-D818-49A3-9494-7319FE9A5BD8}](https://github.com/user-attachments/assets/11f52bcb-b1ca-4f82-9dfc-de5855dcdeaa)
(There is no information displayed below)

Kindly allow me to fix this issue!

**Comment by kshitizvardhan** [comment]
@BowlPulp Go Ahead

**Comment by BowlPulp** [comment]
Done - https://github.com/Open-Source-Chandigarh/SearchMovies/pull/14
