### ISSUE TITLE
Resource Leakage(API KEY)

### ISSUE THREAD

**Issue by AngadSudan** [Open-Source-Chandigarh/SearchMovies#4]
pushed the API KEY in the github repo.
![image](https://github.com/user-attachments/assets/13048150-a9f4-4523-8b46-e3bc577c22ab)

Issues- Resource Leakage
Fixes- Add a .env file and access the API KEY from there.

**Comment by AngadSudan** [comment]
Can you assign this issue to me

**Comment by kshitizvardhan** [comment]
@AngadSudan  Sure, go ahead
